name: NestJS CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Kodni klonlash
      uses: actions/checkout@v3

    - name: Node.js o'rnatish
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Dependenciyalarni o'rnatish
      run: npm ci

    - name: Lint tekshirish
      run: npm run lint

    - name: Testlarni ishga tushirish
      run: npm run test

    - name: Build qilish
      run: npm run build
